apiVersion: v1
kind: Service
metadata:
  annotations:
    sh.ipaas.version: 1.0.0    
  labels:
    sh.ipaas.k8s.svc: wso2am-general-am
  name: wso2am-general-am
spec:
  type: ClusterIP
  ports:  
  - name: "http-admin"
    port: 9443
    targetPort: 9443
  selector:
    sh.ipaas.k8s.pod: wso2am-general

