apiVersion: v1
kind: Service
metadata:
  annotations:
    sh.ipaas.version: 1.0.0    
  labels:
    sh.ipaas.k8s.svc: wso2am-general-gw
  name: wso2am-general-gw  
spec:
  type: ClusterIP
  ports:
  - name: "http-pt"
    port: 8280
    targetPort: 8280
  - name: "https-pt"
    port: 8243
    targetPort: 8243
  selector:
    sh.ipaas.k8s.pod: wso2am-general